Dev
bjorobinson/Sparta-core-project-one pull request #1
Opened 2018-02-06 14:33 UTC by bjorobinson

Pull Request for end of sprint 1

2018-02-06 15:13 UTC, JSChilds commented on POCPs/app.js
> +    // console.log("rest");
Don't leave commented-out code in your final product.

2018-02-06 15:14 UTC, JSChilds requested changes
Functions broadly work, but there are no clear instructions, there's no song to play along to and it doesn't really look presentable as a game.

2018-02-08 16:53 UTC, bjorobinson commented
Pull Request for sprint 2

2018-02-08 16:59 UTC, JSChilds commented on css/style.css
> +
The class above and below are the same, target them both to stop it from being redundant.

2018-02-08 17:00 UTC, JSChilds commented on index.html
> +            PH Text
Put this in a p tag or something, don't have text just in a div.

2018-02-08 17:01 UTC, JSChilds commented on js/app.js
> +$(document).ready(function(){
All your code should be indented within this document.ready function.

2018-02-08 17:01 UTC, JSChilds commented on js/app.js
> +    $("#start_btn").hide();
Semicolons missing from end of lines 6 and 7.

2018-02-08 17:03 UTC, JSChilds commented on README.md
> +# The Game
Put the section about the game first.

2018-02-08 17:03 UTC, JSChilds requested changes
Please make requested changes.

2018-02-08 19:33 UTC, bjorobinson commented
Requested Changes have been made

2018-02-09 09:00 UTC, JSChilds approved these changes

2018-02-09 09:00 UTC, merged